version: '3'

services:
  nginx-laravel:
    container_name: nginx-laravel
    image: nginx:alpine
    ports:
      - 7777:80
    volumes:
      - ./src:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-laravel
      - mysql-laravel

  php-laravel:
    container_name: php-laravel
    build: ./php
    ports:
      - 7888:8000
    volumes:
      - ./src:/var/www/html
    
  mysql-laravel:
    container_name: mysql-laravel
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: $LARAVEL_PASSWORD
      MYSQL_DATABASE: $LARAVEL_DATABASE
    volumes:
      - ./mysql-data:/var/lib/mysql
    
  phpmyadmin-laravel:
    container_name: phpmyadmin-laravel
    image: phpmyadmin/phpmyadmin
    ports:
      - 8009:80
    environment:
      PMA_HOST: mysql-laravel
      MYSQL_PASSWORD: $LARAVEL_PASSWORD

volumes:
  src:
  mysql-data: