version: '3'

services:
  nginx-app:
    container_name: nginx-app
    image: nginx:alpine
    ports:
      - 8888:80
    volumes:
      - ./laravelapp:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app
      - mysql-app

  php-app:
    container_name: php-app
    build: .
    ports:
      - 8008:8000
    volumes:
      - ./laravelapp:/var/www/html
    
  mysql-app:
    container_name: mysql-app
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: $APP_PASSWORD
      MYSQL_DATABASE: $APP_DATABASE
    volumes:
      - ./mysql-data:/var/lib/mysql
    
  phpmyadmin-app:
    container_name: phpmyadmin-app
    image: phpmyadmin/phpmyadmin
    ports:
      - 8009:80
    environment:
      PMA_HOST: mysql-app
      MYSQL_PASSWORD: $APP_PASSWORD
  
volumes:
  laravelapp:
  mysql-data: