version: "3"
services:
  vue-app:
    image: nginx:alpine
    container_name: vue-app
    ports:
      - "8001:80"
    volumes:
      - ./src/dist:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf